spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mingblog?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password:       # 如果没有密码就留空
  mail:
    host: smtp.qq.com
    username: 1602315416@qq.com
    password: kkszhjapwpusgfcg

# 打印 SQL 语句（方便调试）
logging:
  level:
    com.pym.mingblog.mapper: DEBUG
upload:
  path: ./uploads/   # 相对路径，相对于项目根目录（或可写绝对路径如 C:/MingBlog/uploads/）